WITH raw_data AS (
    SELECT 
        QUERY_ID,
        QUERY_START_TIME::TIMESTAMP_LTZ(9) AS QUERY_START_TIME,
        USER_NAME,
        PARENT_QUERY_ID,
        OBJECT_MODIFIED_BY_DDL,
        ROOT_QUERY_ID,
        DIRECT_OBJECT_DOMAIN,
        DIRECT_OBJECT_ID,
        DIRECT_OBJECT_NAME,
        DIRECT_OBJECT_STAGE_KIND,
        BASE_OBJECT_DOMAIN,
        BASE_OBJECT_ID,
        BASE_OBJECT_NAME,
        BASE_OBJECT_STAGE_KIND,
        MODIFIED_OBJECT_DOMAIN,
        MODIFIED_OBJECT_ID,
        MODIFIED_OBJECT_NAME,
        MODIFIED_OBJECT_STAGE_KIND
    FROM {{ source('sf_model', 'FLATTENED_LT_ACCESS_HISTORY') }}
) 
SELECT 
    QUERY_ID,
    QUERY_START_TIME,
    USER_NAME,
    PARENT_QUERY_ID,
    OBJECT_MODIFIED_BY_DDL,
    ROOT_QUERY_ID,
    DIRECT_OBJECT_DOMAIN,
    DIRECT_OBJECT_ID,
    DIRECT_OBJECT_NAME,
    DIRECT_OBJECT_STAGE_KIND,
    BASE_OBJECT_DOMAIN,
    BASE_OBJECT_ID,
    BASE_OBJECT_NAME,
    BASE_OBJECT_STAGE_KIND,
    MODIFIED_OBJECT_DOMAIN,
    MODIFIED_OBJECT_ID,
    MODIFIED_OBJECT_NAME,
    MODIFIED_OBJECT_STAGE_KIND
FROM raw_data
